### ISSUE TITLE
Files can't download

### ISSUE THREAD

**Issue by nevoliu** [devzhk/PINO#13]
Hi Devzhk,

When I download the piececonst_r421_N1024_smooth1.mat file, the web page shows This XML file does not appear to have any style information associated with it. The document tree is shown below.

Is there any other way to download the dataset?

Thanks,
Nevo liu

**Comment by devzhk** [comment]
Hey nevoliu, 

I think the link in the README.md is out of date. I just fix it. Thanks for pointing it out. 
BTW, the other way to download the dataset is to run `download_data.py`. For example, if you want to download the training set of the darcy dataset, run 
```bash
python3 download_data.py --name darcy-train --outdir [the directory to save data]
```
