### ISSUE TITLE
A question about PDE loss for PINO (Burgers equation)

### ISSUE THREAD

**Issue by whDingGit** [devzhk/PINO#3]
Dear devzhk, I'm sorry to bother you. I have been reading your code for PINO on Github and I have a question about the code for computing the PDE loss on fourier domain (for Burgers equation).The original code (FDM_Burgers in losses.py) suggest that the derivative of the signal can be computed with:
ux = irfft{2j*pi*k_x*fft(u)}
I wasn't very familiar with the derivative feature of the discrete fourier transformations. So I tested it with a simple cos function to verify the code (Ground true should be sin function). However, the test seem to reflect that the derivative of the signal should be computed with:
ux = irfft{1j*k_x*fft(u)}
I'm not sure if I was wrong, I have uploaded the code in the txt file, can you elaborate it?
Again, I am sorry to bother you
[TestCode.txt](https://github.com/devzhk/PINO/files/7646234/TestCode.txt)
.

**Comment by XinyuanWang283** [comment]
Hello, Sir, are you doing this stuff right now? Can we discuss the code? My email is xinyuan.wang1999@outlook.com.

**Comment by devzhk** [comment]
> 

Hi, sorry for the late response. I didn't understand your question correctly previously. 
First of all, $u_x = irfft(2 * \pi * j * fft(u))$ is correct. If you haven't figured out, you can take a look at this [blog](https://medium.com/geekculture/numerical-differentiation-via-the-fft-algorithm-calculating-the-spectral-derivative-a8ab18e1abbe). 
Regarding your code, if you plot out the actual derivative, the original code gets the correct gradient.

**Comment by devzhk** [comment]
> Hello, Sir, are you doing this stuff right now? Can we discuss the code? My email is [xinyuan.wang1999@outlook.com](mailto:xinyuan.wang1999@outlook.com).

Hey, thanks for being interested in our work. You can check our paper here https://arxiv.org/pdf/2111.03794.pdf. Feel free to reach out if you are still interested. My email is hzzheng@caltech.edu
