### ISSUE TITLE
piececonst_r421_N1024_smooth1.mat?

### ISSUE THREAD

**Issue by mgraffiedi** [devzhk/PINO#5]
Hello,
I was trying to train PINO on Burger and on Darcy but I obtain the following error.

FileNotFoundError: [Errno 2] No such file or directory: '/mnt/md1/zongyi/piececonst_r421_N1024_smooth1.mat'

I'm not able to understand where that is in the code and or where to find the file.
Any suggestions?

Best

Marco

**Comment by devzhk** [comment]
Hey, 

You may download the data file from the link in the readme and then change the datapath in the configuration file accordingly (configs/pretrain/Darcy-pretrain.yaml).
