### ISSUE TITLE
NS_fft_Re500_T4000.npy 

### ISSUE THREAD

**Issue by mgraffiedi** [devzhk/PINO#6]
I tryed to run the train on NS equations. But, I'm not able to find the file:
NS_fft_Re500_T4000.npy

it's not in the shared drive

Best

M

**Comment by devzhk** [comment]
Hey, that file is too large to put it in my drive. You can download it with this link https://hkzdata.s3.us-west-2.amazonaws.com/PINO/NS_fft_Re500_T4000.npy
