### ISSUE TITLE
MATLAB script to generate the Darcy dataset

### ISSUE THREAD

**Issue by AhmedFrikha** [devzhk/PINO#8]
Hi,
thanks again for sharing the code and links to the datasets. Could you please also share the MATLAB script used to generate the Darcy flow dataset ?

Thanks! :)

**Comment by scaomath** [comment]
Please check [zongyi-li/fourier_neural_operator](https://github.com/zongyi-li/fourier_neural_operator)

See also zongyi-li/fourier_neural_operator#1
