### ISSUE TITLE
Some of the problems about NS_fine_Re500_T128_part0.npy

### ISSUE THREAD

**Issue by qxj233333** [devzhk/PINO#9]
interesting work！

I'm confused about the shape of x in NS_fine_Re500_T128_part0.npy
x
torch.Size([1, 128, 128, 129, 4])
y
torch.Size([1, 128, 128, 129])
why the shape of x is [1, 128, 128, 129, 4] instead of [1, 128, 128, 129]
What does the number 4 mean？

**Comment by devzhk** [comment]
Hi, 

The raw data `NS_fine_Re500_T128_part0.npy`  is of size (100, 129, 128, 128). But we add the positional encoding (x, y, t) so that model knows the position of each points. In other words, the 4 numbers are (u, x, y, t).
